/* eslint-disable camelcase */
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import dotenv from 'dotenv';

dotenv.config();
let baseUrl = '';

if (process.env.NODE_ENV !== 'production') {
  baseUrl = process.env.SENDGRID_DEVELOPMENT__URL;
} else {
  baseUrl = process.env.SENDGRID_PRODUCTION__URL;
}
const Helper = {
  hashPassword(password) {
    return bcrypt.hashSync(password, bcrypt.genSaltSync(8));
  },
  comparePassword(hashPassword, password) {
    return bcrypt.compareSync(password, hashPassword);
  },
  isValidNumber(number) {
    return /^\d+$/.test(number);
  },
  generateToken(user_id, email, is_admin) {
    const token = jwt.sign({
      user_id,
      email,
      is_admin,
    },
    process.env.SECRET, { expiresIn: '7d' });
    return token;
  },
  emailSender(details) {
    const DOMAIN = 'mg.bus-connect.me';
    const mailgun = require('mailgun-js')({ apiKey: process.env.MAILGUN_API_KEY, domain: DOMAIN });

    const data = {
      from: 'admin@mg.bus-connect.me',
      to: details.email,
      subject: details.subject,
      html: details.html,
      'o:tracking': 'False',
    };

    return mailgun.messages().send(data, (error, body) => {
      if (error) {
        console.log(error);
      }
    });
  },

  generateAuthEmail(email, firstName, token) {
    const details = {
      email,
      subject: 'Email Verification - Bus-connect',
      html: `'<div style="width: 90%; margin: 5em auto;
       box-shadow: 0 0 10px rgba(0,0,0,.9);">
        <div>
          <div>
            <div style="background-color: #2084ba; height: 3rem; width: 100%">
                <h2 style="text-align: center; color: white;
                 padding-top: 10px;">Bus-connect</h2>
            </div>
            <h4 style="text-align: center">Hi! ${firstName}</h4>
          </div>
          <div style=" padding: 0px 20px 20px 20px">
            <div>
              <p>Please verify that your email is <strong>${email}</strong>
               when you signed up.</p>
              <p>Click on the button below to verify.</p>
              <button style="color: white; background-color: #2084ba;
               border: none; border-radius: 10px; text-align: center;
                padding: 10px;">
                <a  href="${baseUrl}/api/v1/auth/verifyEmail?token=${token}"
                 style="text-decoration: none;
                 color: white;">Verify Account</a></button>
            </div>
            <div>
              <h3 style="text-align: center">Thank you</h3>
              <h3 style="text-align: center">
              Please do not reply, this is an autogenerated email.</h3>
            </div>
          </div>
        </div>
      </div>`,
    };
    return Helper.emailSender(details);
  },

};

export default Helper;
